# Generated by Django 2.0.3 on 2018-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181105_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='its_pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza'),
        ),
    ]
