# Generated by Django 2.0.3 on 2018-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181105_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='in_pizza', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
