# Generated by Django 2.0.3 on 2018-11-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_topping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(default='small', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(default='small', max_length=64),
        ),
    ]
