# Generated by Django 2.0.3 on 2018-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181109_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[('REGULAR', 'Cheese'), ('_1TOPPING', '1 Topping'), ('_2TOPPING', '2 Toppings'), ('_3TOPPING', '3 Toppings')], default='REGULAR', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('LARGE', 'Large')], default='SMALL', max_length=64),
        ),
    ]
