# Generated by Django 2.0.3 on 2018-11-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181109_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('LARGE', 'Large')], default='SMALL', max_length=64),
        ),
    ]
