# Generated by Django 2.0.3 on 2018-11-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181110_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('LARGE', 'Large')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='in_pizza', to='orders.Topping'),
        ),
    ]
