# Generated by Django 2.0.3 on 2018-11-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181110_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('LARGE', 'Large')], default='SMALL', max_length=64),
        ),
    ]
