# Generated by Django 2.0.3 on 2018-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181110_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(choices=[('IT', 'Italian'), ('CH', 'Cheese'), ('HC', 'Ham + Cheese'), ('MB', 'Meatball'), ('TN', 'Tuna')], default='CH', max_length=64),
        ),
    ]
